# Generated by Django 3.2.3 on 2022-03-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='questao',
            name='data_encerramento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='genero',
        ),
    ]
