# Generated by Django 3.2.3 on 2022-03-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0002_auto_20220316_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativa',
            name='votos',
        ),
        migrations.AddField(
            model_name='alternativa',
            name='ehCorreta',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
