# Generated by Django 3.2.3 on 2022-03-18 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulado', '0003_auto_20220318_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='rotulos',
        ),
        migrations.AddField(
            model_name='questao',
            name='rotulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='simulado.rotulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questao',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='simulado.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True)),
                ('data_publicacao', models.DateTimeField(verbose_name='Data de publicação')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='simulado.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='questao',
            name='simulado',
            field=models.ManyToManyField(blank=True, to='simulado.Simulado'),
        ),
    ]
