# Generated by Django 3.2.3 on 2022-03-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0004_auto_20220318_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='pontuacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questao',
            name='simulado',
            field=models.ManyToManyField(null=True, to='simulado.Simulado'),
        ),
    ]
