# Generated by Django 3.2.3 on 2022-03-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0005_auto_20220320_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='ehCorreta',
            field=models.BooleanField(default=False),
        ),
    ]
