# Generated by Django 3.2.3 on 2022-03-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0006_alter_alternativa_ehcorreta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativa',
            name='ehCorreta',
        ),
        migrations.AddField(
            model_name='alternativa',
            name='correta',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
