# Generated by Django 3.2.3 on 2022-03-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0009_alter_alternativa_correta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='correta',
            field=models.BooleanField(default=False),
        ),
    ]
