# Generated by Django 3.2.3 on 2022-03-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0012_alter_alternativa_correta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='simulado',
            field=models.ManyToManyField(blank=True, null=True, to='simulado.Simulado'),
        ),
    ]
