# Generated by Django 3.2.3 on 2022-03-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0014_alter_questao_pontuacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questao',
            name='simulado',
        ),
        migrations.AddField(
            model_name='simulado',
            name='questao',
            field=models.ManyToManyField(blank=True, null=True, to='simulado.Questao'),
        ),
    ]
