# Generated by Django 3.2.3 on 2022-03-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0015_auto_20220320_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulado',
            name='questao',
            field=models.ManyToManyField(blank=True, null=True, related_name='simulado', to='simulado.Questao'),
        ),
    ]
