# Generated by Django 3.2.3 on 2022-03-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0016_alter_simulado_questao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('simulado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='simulado.simulado')),
            ],
        ),
    ]
