# Generated by Django 3.2.3 on 2022-03-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0017_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='simulado.usuario'),
            preserve_default=False,
        ),
    ]
