# Generated by Django 3.2.3 on 2022-03-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0019_alter_resultado_simulado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='nota',
            field=models.FloatField(),
        ),
    ]
