# Generated by Django 3.2.3 on 2022-03-21 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simulado', '0020_alter_resultado_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='data_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de publicação'),
            preserve_default=False,
        ),
    ]
